### ISSUE TITLE
[IE Issue] Not rendering in IE7/IE8

### ISSUE THREAD

**Issue by netprod** [alkemann/CakePHP-Assets#6] opened 2010-04-28 06:12 UTC
Hi all,
Great helper but i'm experiencing problem when trying to render a chart in IE8...
No problems on other Web Navigators (Safari, Opera, Firefox, Google Chrome).

I've got 4 charts to display.
In my ses_controller.php i generate datas : 

<pre><code>
<?php  
$annee_en_cours = 2006; //intval(date('Y')); 
        $annee_precedente = 2005; //intval(date('Y'))-1; 
        $mois = 12; //intval(date('m')); 
         
        $this->set('ctrl_conf', $this->Se->getCountCtrl('ctrlconf', $annee_en_cours, $mois)); 
        $this->set('ctrl_elec', $this->Se->getCountCtrl('ctrlelec', $annee_en_cours, $mois)); 
        $this->set('ctrl_fonc', $this->Se->getCountCtrl('ctrlfonc', $annee_en_cours, $mois)); 
        $this->set('ctrl_final', $this->Se->getCountCtrl('ctrlfinal', $annee_en_cours, $mois)); 
        $this->set('ctrl_conf_precedente', $this->Se->getCountCtrl('ctrlconf', $annee_precedente, $mois)); 
        $this->set('ctrl_elec_precedente', $this->Se->getCountCtrl('ctrlelec', $annee_precedente, $mois)); 
        $this->set('ctrl_fonc_precedente', $this->Se->getCountCtrl('ctrlfonc', $annee_precedente, $mois)); 
        $this->set('ctrl_final_precedente', $this->Se->getCountCtrl('ctrlfinal', $annee_precedente, $mois)); 
        $this->set('ctrl_conf_se', $this->Se->getDetailCtrl('ctrlconf', $annee_en_cours, $mois)); 
        $this->set('ctrl_elec_se', $this->Se->getDetailCtrl('ctrlelec', $annee_en_cours, $mois)); 
        $this->set('ctrl_fonc_se', $this->Se->getDetailCtrl('ctrlfonc', $annee_en_cours, $mois)); 
        $this->set('ctrl_final_se', $this->Se->getDetailCtrl('ctrlfinal', $annee_en_cours, $mois)); 
        $this->set('annee_en_cours', $annee_en_cours); 
        $this->set('annee_precedente', $annee_precedente); 
?>
</code></pre>

In my main view : 

<pre><code>
<?php  
<div id="content_right"> 
    <div> 
        <div style="float:left;width:50%"> 
            <div class="cbb"> 
                <div> 
                     
                    <div id="content_titre"> 
                        <h1 class="cbb_h1" onclick="toggle_menu('ctrlConf')">Contr&ocirc;les Configurations</h1> 
                    </div> 
                     
                    <div id="content_toggle"> 
                        <img src="http://gwprod/img/remove.png" border="0" id="ctrlConf_titre_toggle" onclick="toggle_menu('ctrlConf')"> 
                    </div> 
                </div> 
                <div style="clear:both;"></div> 
                <?php  
                echo $flashChart->begin(array('prototype'=>true)); 
                 
                // Construction des labels en x 
                $months[0] = "Jan"; 
                $months[1] = "Fev"; 
                $months[2] = "Mar"; 
                $months[3] = "Avr"; 
                $months[4] = "Mai"; 
                $months[5] = "Jui"; 
                $months[6] = "Jui"; 
                $months[7] = "Aou"; 
                $months[8] = "Sep"; 
                $months[9] = "Oct"; 
                $months[10] = "Nov"; 
                $months[11] = "Dec";  
                 
                for($i=0; $i<count($ctrl_conf); $i++) 
                    $data_x[$i] = $months[$i]; 
                ?> 
                <?php  
                    echo $this->element('ses/stats_ctrl', array( 
                        'graphDivId'            => 'ctrlConf', 
                        'detailDivId'            => 'detail_ctrl_conf', 
                        'data_x'                => $data_x, 
                        'ctrl_annee_en_cours'    => $ctrl_conf, 
                        'ctrl_annee_precedente'    => $ctrl_conf_precedente, 
                        'ctrl_detail'            => $ctrl_conf_se 
                    ));  
                ?>     
            </div> 
            <div class="cbb"> 
                <div> 
                     
                    <div id="content_titre"> 
                        <h1 class="cbb_h1" onclick="toggle_menu('ctrlElec')">Contr&ocirc;les Electriques</h1>
                    </div> 
                     
                    <div id="content_toggle"> 
                        <img src="http://gwprod/img/remove.png" border="0" id="ctrlElec_titre_toggle" onclick="toggle_menu('ctrlElec')">
                    </div> 
                </div> 
                <div style="clear:both;"></div> 
                <?php  
                    echo $this->element('ses/stats_ctrl', array( 
                        'graphDivId'            => 'ctrlElec', 
                        'detailDivId'            => 'detail_ctrl_elec', 
                        'data_x'                => $data_x, 
                        'ctrl_annee_en_cours'    => $ctrl_elec, 
                        'ctrl_annee_precedente'    => $ctrl_elec_precedente, 
                        'ctrl_detail'            => $ctrl_elec_se 
                    ));  
                ?> 
            </div>         
        </div> 
        <div style="float:left;width:50%"> 
            <div class="cbb"> 
                <div> 
                     
                    <div id="content_titre"> 
                        <h1 class="cbb_h1" onclick="toggle_menu('ctrlFonc')">Contr&ocirc;les Fonctionnels</h1>
                    </div> 
                     
                    <div id="content_toggle"> 
                        <img src="http://gwprod/img/remove.png" border="0" id="ctrlFonc_titre_toggle" onclick="toggle_menu('ctrlFonc')">
                    </div> 
                </div> 
                <div style="clear:both;"></div> 
                <?php  
                    echo $this->element('ses/stats_ctrl', array( 
                        'graphDivId'            => 'ctrlFonc', 
                        'detailDivId'            => 'detail_ctrl_fonc', 
                        'data_x'                => $data_x, 
                        'ctrl_annee_en_cours'    => $ctrl_fonc, 
                        'ctrl_annee_precedente'    => $ctrl_fonc_precedente, 
                        'ctrl_detail'            => $ctrl_fonc_se 
                    ));  
                ?> 
            </div> 
            <div class="cbb"> 
                <div> 
                     
                    <div id="content_titre"> 
                        <h1 class="cbb_h1" onclick="toggle_menu('ctrlFinal')">Contr&ocirc;les Finaux</h1>
                    </div> 
                     
                    <div id="content_toggle"> 
                        <img src="http://gwprod/img/remove.png" border="0" id="ctrlFinal_titre_toggle" onclick="toggle_menu('ctrlFinal')">
                    </div> 
                </div> 
                <div style="clear:both;"></div> 
                <?php  
                    echo $this->element('ses/stats_ctrl', array( 
                        'graphDivId'            => 'ctrlFinal', 
                        'detailDivId'            => 'detail_ctrl_final', 
                        'data_x'                => $data_x, 
                        'ctrl_annee_en_cours'    => $ctrl_final, 
                        'ctrl_annee_precedente'    => $ctrl_final_precedente, 
                        'ctrl_detail'            => $ctrl_final_se 
                    ));  
                ?> 
            </div> 
        </div> 
    </div> 
</div> 
?>
</code></pre>

in my stats_ctrl element : 

<pre><code>
<?php  
<div id="<?php echo $graphDivId; ?>" align="center"> 
        <?php 
        // Controles de configurations   
        $flashChart->setData($ctrl_annee_en_cours, '{n}', false, 'stuff'.$graphDivId, 'data'.$graphDivId);   
        $flashChart->axis('y',array('range' => array(0, max($ctrl_annee_en_cours)+1, 1)));      
        $flashChart->axis('x',array('labels' => $data_x), array('vertical' => false ));      
                  
        echo $flashChart->chart('bar_glass', array(), 'stuff'.$graphDivId, 'data'.$graphDivId);   
        echo $flashChart->render(425, 200, 'data'.$graphDivId, $graphDivId);   
    ?> 
    </div> 
?>
</code></pre>

It renders perfectly in Chrome, Safari or other but not in IE7 or 8 !!

AnyOne has got an idea ?

**Comment by alkemann** [comment] 2010-04-30 22:40
yea the problem isnt the php code, but flash or javascript. go to the flashchart homepage and see if you can run those examples in the same ie7 installation. if you can, compare rendered code. If this does not help, supply more information than "not"

**Comment by alkemann** [comment] 2010-07-07 14:35
closing pending more information

**Closed as completed by alkemann** 2010-07-07 14:35 UTC
